### ISSUE TITLE
Wits End

### ISSUE THREAD

**Issue by KarmicKnight** [xavierwg13/LeagueItemsRoR2#1]
Could you add a config to change wits end to not have movement speed on hit? I had a commando run with wits end and it was unplayable with the amount of movement speed gained from a single burst fire.

**Comment by Valoneu** [comment]
or add separate config for attackspeed and movement speed. i just wanted to ask this xd.

**Comment by shirograhm** [comment]
Added separate config for each value in 0.9.6.
